apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mend-renovate-ce
  namespace: renovate-system
spec:
  chart:
    spec:
      chart: mend-renovate-ce
      sourceRef:
        kind: HelmRepository
        name: mend-renovate
      version: 11.0.0
  interval: 1h0m0s
  releaseName: mend-renovate-ce
  targetNamespace: renovate-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: Secret
      name: renovate-secrets
      optional: false
