apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: flux-system
spec:
  interval: 1h0m0s
  releaseName: sealed-secrets-controller
  targetNamespace: flux-system
  sourceRef:
    kind: HelmRepository
    name: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      version: ">=1.15.0-0"
  crds: CreateReplace
  