apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep-data-pvc
  namespace: karakeep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn