apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-downloads-pvc
  namespace: sabnzbd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: spinning-rust
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config-pvc
  namespace: sabnzbd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
